apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: recommendationservice
spec:
  namespaceTagSuffix: true
  environments:
    default:
      defaultNamespace: hipster-shop
      server: https://158.160.12.247
    dev:
      defaultNamespace: hipster-shop    
      server: https://158.160.12.247
  vars: {}
