apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
      env:
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio
            key: username
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio
            key: password

